### ISSUE TITLE
SDL2.dll not found

### ISSUE THREAD

**Issue by GregRGM** [jaysherson/ProjectAbyss#19]
Upon opening charles.exe in Build-12519, I get the error "The code execution cannot proceed because SDL2.dll was not found. Reinstalling the program may fix this problem."

I get other error popups that include glew32, assimp-vc140-mt, and another SDL2, all dlls. The editor then closes.

This happens on my desktop PC.

**Comment by timotheyg** [comment]
This should be fixed now in Build-190125-50bead along with other quality of life changes
