### ISSUE TITLE
Debug Assertation Failed when loading level

### ISSUE THREAD

**Issue by GregRGM** [jaysherson/ProjectAbyss#21]
![debugassfailed](https://user-images.githubusercontent.com/30060640/51804908-36c74080-221b-11e9-872c-05160edd98bf.png)
I imported North's StructuredLevel1 into Assets/levels/ and opened it. I get the crash message "Debug Assertation Failed"

**Comment by timotheyg** [comment]
That seems to be due to missing assets, I'll make it so that prints an error message, but you should make sure that everything is where it should be

**Comment by timotheyg** [comment]
Future Crashes Avoided, Level loading properly on Greg's Machine
